### ISSUE TITLE
从io.Reader上传，下载返回io.Reader

### ISSUE THREAD

**Issue by myml** [chyroc/go-aliyundrive#10]
现在是基于文件的方式，不是很灵活，如果先保存到临时文件，有一定的性能损失

**Comment by myml** [comment]
我抽时间添加这个

**Comment by myml** [comment]
https://github.com/chyroc/go-aliyundrive/pull/13

**Comment by hellojukay** [comment]
看起来这个问题已经解决了，可以关闭 issue 了
